'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { extractErrorMessage } from '@/lib/api';

interface RtuFormData {
  ip_address: string;
}

interface PrefillData {
  ip_address?: string;
  station_name?: string;
  vendor_id?: string;
  device_id?: string;
}

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (rtu: RtuFormData) => void;
  prefillData?: PrefillData;
}

function validateIpAddress(value: string): string | null {
  if (!value.trim()) {
    return 'IP address is required';
  }
  const ipv4Regex = /^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;
  if (!ipv4Regex.test(value)) {
    return 'Enter a valid IPv4 address (e.g., 192.168.1.100)';
  }
  return null;
}

export default function AddRtuModal({
  isOpen,
  onClose,
  onSuccess,
  prefillData,
}: Props) {
  const [ipAddress, setIpAddress] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [touched, setTouched] = useState(false);
  const modalRef = useRef<HTMLDivElement>(null);

  // Handle escape key to close modal
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !loading) {
        onClose();
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    document.body.style.overflow = 'hidden';
    modalRef.current?.focus();

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = '';
    };
  }, [isOpen, loading, onClose]);

  // Reset form when modal opens/closes or prefill data changes
  useEffect(() => {
    if (isOpen) {
      setIpAddress(prefillData?.ip_address || '');
      setError(null);
      setTouched(false);
    }
  }, [isOpen, prefillData]);

  const handleChange = useCallback((value: string) => {
    setIpAddress(value);
    setError(null);

    if (touched) {
      const validationError = validateIpAddress(value);
      setError(validationError);
    }
  }, [touched]);

  const handleBlur = useCallback(() => {
    setTouched(true);
    const validationError = validateIpAddress(ipAddress);
    setError(validationError);
  }, [ipAddress]);

  const handleSubmit = async () => {
    const validationError = validateIpAddress(ipAddress);
    if (validationError) {
      setError(validationError);
      setTouched(true);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Build request - only ip_address is required
      // station_name auto-generated by backend from IP
      // vendor_id and device_id use prefill (from discovery) or backend defaults
      const requestBody: Record<string, string> = {
        ip_address: ipAddress,
      };

      // Include station_name if provided by discovery
      if (prefillData?.station_name) {
        requestBody.station_name = prefillData.station_name;
      }

      // Include vendor/device IDs if provided by discovery prefill
      if (prefillData?.vendor_id) {
        requestBody.vendor_id = prefillData.vendor_id;
      }
      if (prefillData?.device_id) {
        requestBody.device_id = prefillData.device_id;
      }

      const res = await fetch('/api/v1/rtus', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody),
      });

      if (res.status === 201 || res.ok) {
        onSuccess({ ip_address: ipAddress });
        return;
      }

      // Handle errors
      const data = await res.json();
      const errorMsg = extractErrorMessage(data.detail, 'Failed to add RTU');
      setError(errorMsg);
    } catch {
      setError('Unable to reach server. Check connection and try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    if (!loading) {
      onClose();
    }
  };

  if (!isOpen) return null;

  const isFromDiscovery = !!(prefillData?.vendor_id || prefillData?.device_id || prefillData?.station_name);

  // Handle backdrop click
  const handleBackdropClick = (event: React.MouseEvent) => {
    if (event.target === event.currentTarget && !loading) {
      onClose();
    }
  };

  return (
    <div
      className="fixed inset-0 bg-black/70 flex items-center justify-center z-modal p-4"
      onClick={handleBackdropClick}
    >
      <div
        ref={modalRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="add-rtu-modal-title"
        tabIndex={-1}
        className="bg-gray-900 rounded-lg w-full max-w-md border border-gray-700 shadow-xl outline-none"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-700">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-blue-600/20 flex items-center justify-center">
              <span className="text-blue-400 text-xl font-bold">+</span>
            </div>
            <div>
              <h2 id="add-rtu-modal-title" className="text-lg font-semibold text-white">Add New RTU</h2>
              {isFromDiscovery && (
                <p className="text-xs text-green-400">From network discovery</p>
              )}
            </div>
          </div>
          <button
            onClick={handleClose}
            disabled={loading}
            className="text-gray-400 hover:text-white transition-colors disabled:opacity-50 w-6 h-6 flex items-center justify-center text-lg font-bold"
          >
            &times;
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-4 space-y-4">
          {/* IP Address */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">
              IP Address <span className="text-red-400">*</span>
            </label>
            <input
              type="text"
              value={ipAddress}
              onChange={e => handleChange(e.target.value)}
              onBlur={handleBlur}
              placeholder="e.g., 192.168.1.100"
              disabled={loading}
              autoFocus
              className={`w-full px-3 py-2 bg-gray-800 border rounded text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50 ${
                error ? 'border-red-500' : 'border-gray-700'
              }`}
            />
            {error && (
              <p className="text-red-400 text-xs mt-1">{error}</p>
            )}
            <p className="text-gray-500 text-xs mt-1">
              {isFromDiscovery
                ? 'Station name provided by device discovery'
                : 'Use DCP Scan or Ping Scan to discover devices first'}
            </p>
          </div>

          {/* Discovery info (read-only, shown only if from discovery) */}
          {isFromDiscovery && (
            <div className="p-3 bg-gray-800/50 border border-gray-700 rounded-lg">
              <p className="text-xs text-gray-400 mb-2">Discovered device info:</p>
              <div className="space-y-1 text-xs">
                {prefillData?.station_name && (
                  <div>
                    <span className="text-gray-500">Device Name:</span>
                    <span className="text-gray-300 font-mono ml-1">{prefillData.station_name}</span>
                  </div>
                )}
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <span className="text-gray-500">Vendor ID:</span>
                    <span className="text-gray-300 font-mono ml-1">{prefillData?.vendor_id || '0x0000'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">Device ID:</span>
                    <span className="text-gray-300 font-mono ml-1">{prefillData?.device_id || '0x0000'}</span>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-3 px-6 py-4 border-t border-gray-700">
          <button
            onClick={handleClose}
            disabled={loading}
            className="px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded text-white transition-colors disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={loading || !!error}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded text-white font-medium transition-colors disabled:opacity-50 flex items-center gap-2"
          >
            {loading && (
              <span className="inline-block animate-pulse">...</span>
            )}
            {loading ? 'Adding...' : 'Add RTU'}
          </button>
        </div>
      </div>
    </div>
  );
}
