#!/bin/bash
# =============================================================================
# Water Treatment Controller - Docker Build Environment Generator
# =============================================================================
# Generates .env file with git version information for Docker builds.
#
# Usage:
#   ./generate-build-env.sh              # Generate .env in current directory
#   ./generate-build-env.sh /path/to/dir # Generate .env in specified directory
#
# Docker Compose automatically loads .env files from the same directory as
# docker-compose.yml, so this ensures GIT_COMMIT and GIT_DATE are always
# available for builds even when not using bootstrap.sh.
#
# Copyright (C) 2024-2026
# SPDX-License-Identifier: GPL-3.0-or-later
# =============================================================================

set -euo pipefail

# Determine output directory
OUTPUT_DIR="${1:-$(dirname "$0")}"
ENV_FILE="$OUTPUT_DIR/.env"

# Get repository root (parent of docker directory)
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "Generating Docker build environment..."
echo "  Repository: $REPO_ROOT"
echo "  Output: $ENV_FILE"

# Check if we're in a git repository
if [[ ! -d "$REPO_ROOT/.git" ]]; then
    echo "WARNING: Not in a git repository, using 'unknown' for version info"
    GIT_COMMIT="unknown"
    GIT_DATE="unknown"
else
    # Get git commit info
    if ! command -v git &>/dev/null; then
        echo "WARNING: git command not found, using 'unknown' for version info"
        GIT_COMMIT="unknown"
        GIT_DATE="unknown"
    else
        GIT_COMMIT=$(git -C "$REPO_ROOT" rev-parse --short=7 HEAD 2>/dev/null || echo "unknown")
        GIT_DATE=$(git -C "$REPO_ROOT" log -1 --format=%ci HEAD 2>/dev/null || echo "unknown")
    fi
fi

# Generate .env file
cat > "$ENV_FILE" << EOF
# Water Treatment Controller - Docker Build Environment
# Auto-generated by generate-build-env.sh on $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)
# DO NOT EDIT MANUALLY - This file is regenerated before each build

# Git version information for controller binary
GIT_COMMIT=$GIT_COMMIT
GIT_DATE=$GIT_DATE

# Port configuration (can be overridden)
WTC_API_PORT=8000
WTC_UI_PORT=8080
WTC_DB_PORT=5432
WTC_GRAFANA_PORT=3000
WTC_OPENPLC_PORT=8081
WTC_DOCKER_UI_INTERNAL_PORT=3000

# Service configuration
WTC_CYCLE_TIME=1000
WTC_LOG_LEVEL=INFO
WTC_STARTUP_MODE=production
WTC_API_ONLY=true
WTC_USE_PYTHON_CONTROLLER=1

# Passwords (development/test only - see CLAUDE.md)
GRAFANA_PASSWORD=admin
DB_PASSWORD=wtc_password
EOF

echo "✓ Generated $ENV_FILE"
echo "  GIT_COMMIT=$GIT_COMMIT"
echo "  GIT_DATE=$GIT_DATE"
echo ""
echo "You can now run: docker compose build"
echo "The .env file will be automatically loaded by Docker Compose."
