"""
Water Treatment Controller - Database Persistence Layer (Compatibility Shim)
Copyright (C) 2024
SPDX-License-Identifier: GPL-3.0-or-later

DEPRECATED: This module is kept for backward compatibility.
Use `from app.persistence import ...` instead.

The persistence layer has been refactored into focused modules:
  app/persistence/base.py      - Database connection, schema initialization
  app/persistence/rtu.py       - RTU devices, sensors, controls
  app/persistence/alarms.py    - Alarm rules, shelved alarms
  app/persistence/pid.py       - PID control loops
  app/persistence/modbus.py    - Modbus server config, devices, mappings
  app/persistence/sessions.py  - User session management
  app/persistence/users.py     - User management, authentication
  app/persistence/historian.py - Historian tags, slot configurations
  app/persistence/config.py    - Log forwarding, AD config, backups, import/export
  app/persistence/discovery.py - DCP discovery cache
  app/persistence/audit.py     - Audit log, command log
"""

# Re-export everything from the new modular package with explicit imports
from app.persistence import (
    DB_PATH,
    USER_SYNC_SALT,
    authenticate_user,
    cleanup_expired_sessions,
    cleanup_expired_shelves,
    clear_discovery_cache,
    clear_old_command_logs,
    clear_rtu_controls,
    clear_rtu_sensors,
    create_alarm_rule,
    create_backup_record,
    create_modbus_downstream_device,
    create_modbus_register_mapping,
    create_pid_loop,
    create_rtu_device,
    create_session,
    create_user,
    delete_alarm_rule,
    delete_backup_record,
    delete_historian_tag,
    delete_modbus_downstream_device,
    delete_modbus_register_mapping,
    delete_pid_loop,
    delete_rtu_control,
    delete_rtu_device,
    delete_rtu_sensor,
    delete_session,
    delete_session_by_prefix,
    delete_slot_config,
    delete_user,
    ensure_default_admin,
    export_configuration,
    get_active_sessions,
    get_ad_config,
    get_alarm_rule,
    get_alarm_rules,
    get_all_slot_configs,
    get_audit_log,
    get_backup,
    get_backups,
    get_command_log,
    get_command_log_count,
    get_db,
    get_discovered_devices,
    get_historian_tag,
    get_historian_tag_by_name,
    get_historian_tags,
    get_log_forwarding_config,
    get_modbus_downstream_devices,
    get_modbus_register_mappings,
    get_modbus_server_config,
    get_pid_loop,
    get_pid_loops,
    get_rtu_controls,
    get_rtu_device,
    get_rtu_devices,
    get_rtu_inventory,
    get_rtu_sensors,
    get_session,
    get_shelved_alarm,
    get_shelved_alarms,
    get_slot_config,
    get_slot_configs_by_rtu,
    get_user,
    get_user_by_username,
    get_users,
    get_users_for_sync,
    hash_password,
    import_configuration,
    init_database,
    initialize,
    is_alarm_shelved,
    is_initialized,
    log_audit,
    log_command,
    mark_device_as_added,
    shelve_alarm,
    unshelve_alarm,
    update_ad_config,
    update_alarm_rule,
    update_command_result,
    update_control_state,
    update_log_forwarding_config,
    update_modbus_downstream_device,
    update_modbus_register_mapping,
    update_modbus_server_config,
    update_pid_loop,
    update_pid_mode,
    update_pid_setpoint,
    update_rtu_device,
    update_sensor_value,
    update_session_activity,
    update_user,
    upsert_discovered_device,
    upsert_historian_tag,
    upsert_rtu_control,
    upsert_rtu_sensor,
    upsert_slot_config,
    verify_password,
)

# Explicit re-exports for tools that check __all__
__all__ = [
    'DB_PATH',
    'USER_SYNC_SALT',
    'authenticate_user',
    'cleanup_expired_sessions',
    'cleanup_expired_shelves',
    'clear_discovery_cache',
    'clear_old_command_logs',
    'clear_rtu_controls',
    'clear_rtu_sensors',
    'create_alarm_rule',
    'create_backup_record',
    'create_modbus_downstream_device',
    'create_modbus_register_mapping',
    'create_pid_loop',
    'create_rtu_device',
    'create_session',
    'create_user',
    'delete_alarm_rule',
    'delete_backup_record',
    'delete_historian_tag',
    'delete_modbus_downstream_device',
    'delete_modbus_register_mapping',
    'delete_pid_loop',
    'delete_rtu_control',
    'delete_rtu_device',
    'delete_rtu_sensor',
    'delete_session',
    'delete_session_by_prefix',
    'delete_slot_config',
    'delete_user',
    'ensure_default_admin',
    'export_configuration',
    'get_active_sessions',
    'get_ad_config',
    'get_alarm_rule',
    'get_alarm_rules',
    'get_all_slot_configs',
    'get_audit_log',
    'get_backup',
    'get_backups',
    'get_command_log',
    'get_command_log_count',
    'get_db',
    'get_discovered_devices',
    'get_historian_tag',
    'get_historian_tag_by_name',
    'get_historian_tags',
    'get_log_forwarding_config',
    'get_modbus_downstream_devices',
    'get_modbus_register_mappings',
    'get_modbus_server_config',
    'get_pid_loop',
    'get_pid_loops',
    'get_rtu_controls',
    'get_rtu_device',
    'get_rtu_devices',
    'get_rtu_inventory',
    'get_rtu_sensors',
    'get_session',
    'get_shelved_alarm',
    'get_shelved_alarms',
    'get_slot_config',
    'get_slot_configs_by_rtu',
    'get_user',
    'get_user_by_username',
    'get_users',
    'get_users_for_sync',
    'hash_password',
    'import_configuration',
    'init_database',
    'initialize',
    'is_alarm_shelved',
    'is_initialized',
    'log_audit',
    'log_command',
    'mark_device_as_added',
    'shelve_alarm',
    'unshelve_alarm',
    'update_ad_config',
    'update_alarm_rule',
    'update_command_result',
    'update_control_state',
    'update_log_forwarding_config',
    'update_modbus_downstream_device',
    'update_modbus_register_mapping',
    'update_modbus_server_config',
    'update_pid_loop',
    'update_pid_mode',
    'update_pid_setpoint',
    'update_rtu_device',
    'update_sensor_value',
    'update_session_activity',
    'update_user',
    'upsert_discovered_device',
    'upsert_historian_tag',
    'upsert_rtu_control',
    'upsert_rtu_sensor',
    'upsert_slot_config',
    'verify_password',
]
